
version: '3'

services:

  shard1svr1:
    container_name: shard1svr1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - ./mongo/shard1svr1/data:/data/db

  shard1svr2:
    container_name: shard1svr2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - ./mongo/shard1svr2/data:/data/db

  shard1svr3:
    container_name: shard1svr3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - ./mongo/shard1svr3/data:/data/db
  setup-rs:
    image: "setup-rs"
    build: ./setup
    depends_on:
      - shard1svr1
# volumes:
#   shard1svr1:
#   shard1svr2:
#   shard1svr3:

