FROM node:21
WORKDIR /app
COPY ./search-app/package.json ./
ARG NODE_ENV 
RUN if [ "$NODE_ENV" = "development " ]; \
    then npm install; \
    else npm install --only=production; \
    fi
COPY ./search-app ./
ENV PORT 8081
EXPOSE $PORT
CMD ["node", "server.js"]


