version: '3.8'
services: 
  nginx:
    ports:
      - "8080:80"
  user-app:
    build: 
      context: . 
      args:
        NODE_ENV: development
    volumes:
      - ./user-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
    command: npm run dev
