version: '3.8'
services: 
  nginx:
    ports:
      - "8080:80"
  user-app:
    build: 
      context: . 
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node server.js
