
version: '3'

services:

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - ./mongo/shard2svr1/data:/data/db

  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - ./mongo/shard2svr2/data:/data/db

  shard2svr3:
    container_name: shard2svr3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - ./mongo/shard2svr3/data:/data/db
  setup-rs:
    image: "setup-rs"
    build: ./setup
    depends_on:
      - shard2svr1

# volumes:
#   shard2svr1:
#   shard2svr2:
#   shard2svr3:
